import { z } from "zod";
export declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "staging", "production"]>>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["debug", "info", "warn", "error"]>>;
    DATABASE_URL: z.ZodString;
    REDIS_URL: z.ZodString;
    API_HOST: z.ZodDefault<z.ZodString>;
    API_PORT: z.ZodDefault<z.ZodNumber>;
    WEB_PORT: z.ZodDefault<z.ZodNumber>;
    WORKER_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    DEFAULT_TENANT_SLUG: z.ZodString;
    JWT_ISSUER: z.ZodString;
    JWT_AUDIENCE: z.ZodString;
    JWT_PUBLIC_KEY: z.ZodString;
    JWT_PRIVATE_KEY: z.ZodString;
    INTEGRATION_NETSUITE_CLIENT_ID: z.ZodOptional<z.ZodString>;
    INTEGRATION_NETSUITE_CLIENT_SECRET: z.ZodOptional<z.ZodString>;
    INTEGRATION_NETSUITE_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    INTEGRATION_NETSUITE_BASE_URL: z.ZodOptional<z.ZodString>;
    INTEGRATION_QUICKBOOKS_CLIENT_ID: z.ZodOptional<z.ZodString>;
    INTEGRATION_QUICKBOOKS_CLIENT_SECRET: z.ZodOptional<z.ZodString>;
    INTEGRATION_QUICKBOOKS_REALM_ID: z.ZodOptional<z.ZodString>;
    INTEGRATION_XERO_CLIENT_ID: z.ZodOptional<z.ZodString>;
    INTEGRATION_XERO_CLIENT_SECRET: z.ZodOptional<z.ZodString>;
    INTEGRATION_XERO_TENANT_ID: z.ZodOptional<z.ZodString>;
    INTEGRATION_ZOHO_CLIENT_ID: z.ZodOptional<z.ZodString>;
    INTEGRATION_ZOHO_CLIENT_SECRET: z.ZodOptional<z.ZodString>;
    INTEGRATION_ZOHO_ORGANIZATION_ID: z.ZodOptional<z.ZodString>;
    INTEGRATION_ODOO_BASE_URL: z.ZodOptional<z.ZodString>;
    INTEGRATION_ODOO_DATABASE: z.ZodOptional<z.ZodString>;
    INTEGRATION_ODOO_USERNAME: z.ZodOptional<z.ZodString>;
    INTEGRATION_ODOO_PASSWORD: z.ZodOptional<z.ZodString>;
    INTEGRATION_ODOO_COMPANY_ID: z.ZodOptional<z.ZodString>;
    INTEGRATION_ODOO_DEFAULT_JOURNAL_ID: z.ZodOptional<z.ZodString>;
    INTEGRATION_ODOO_DEFAULT_PRODUCT_ID: z.ZodOptional<z.ZodString>;
    INTEGRATION_DEAR_ACCOUNT_ID: z.ZodOptional<z.ZodString>;
    INTEGRATION_DEAR_API_KEY: z.ZodOptional<z.ZodString>;
    INTEGRATION_GOOGLE_SHEETS_CLIENT_EMAIL: z.ZodOptional<z.ZodString>;
    INTEGRATION_GOOGLE_SHEETS_PRIVATE_KEY: z.ZodOptional<z.ZodString>;
    INTEGRATION_GOOGLE_SHEETS_SPREADSHEET_ID: z.ZodOptional<z.ZodString>;
    INTEGRATION_EMAIL_HOST: z.ZodOptional<z.ZodString>;
    INTEGRATION_EMAIL_PORT: z.ZodOptional<z.ZodNumber>;
    INTEGRATION_EMAIL_USERNAME: z.ZodOptional<z.ZodString>;
    INTEGRATION_EMAIL_PASSWORD: z.ZodOptional<z.ZodString>;
    INTEGRATION_EMAIL_MAILBOX: z.ZodOptional<z.ZodString>;
    INTEGRATION_YIELD_PROJECT_ID: z.ZodOptional<z.ZodString>;
    INTEGRATION_YIELD_REGION: z.ZodOptional<z.ZodString>;
    INTEGRATION_PERFIOS_API_KEY: z.ZodOptional<z.ZodString>;
    INTEGRATION_PERFIOS_BASE_URL: z.ZodOptional<z.ZodString>;
    INTEGRATION_BUSINESS_CENTRAL_BASE_URL: z.ZodOptional<z.ZodString>;
    INTEGRATION_BUSINESS_CENTRAL_CONNECT_CLIENT_ID: z.ZodOptional<z.ZodString>;
    INTEGRATION_BUSINESS_CENTRAL_CONNECT_CLIENT_SECRET: z.ZodOptional<z.ZodString>;
    INTEGRATION_BUSINESS_CENTRAL_CONNECT_REDIRECT_URI: z.ZodOptional<z.ZodString>;
    INTEGRATION_BUSINESS_CENTRAL_CONNECT_DEFAULT_ENVIRONMENT: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "staging" | "production";
    LOG_LEVEL: "info" | "error" | "debug" | "warn";
    DATABASE_URL: string;
    REDIS_URL: string;
    API_HOST: string;
    API_PORT: number;
    WEB_PORT: number;
    WORKER_CONCURRENCY: number;
    DEFAULT_TENANT_SLUG: string;
    JWT_ISSUER: string;
    JWT_AUDIENCE: string;
    JWT_PUBLIC_KEY: string;
    JWT_PRIVATE_KEY: string;
    INTEGRATION_NETSUITE_CLIENT_ID?: string | undefined;
    INTEGRATION_NETSUITE_CLIENT_SECRET?: string | undefined;
    INTEGRATION_NETSUITE_ACCOUNT_ID?: string | undefined;
    INTEGRATION_NETSUITE_BASE_URL?: string | undefined;
    INTEGRATION_QUICKBOOKS_CLIENT_ID?: string | undefined;
    INTEGRATION_QUICKBOOKS_CLIENT_SECRET?: string | undefined;
    INTEGRATION_QUICKBOOKS_REALM_ID?: string | undefined;
    INTEGRATION_XERO_CLIENT_ID?: string | undefined;
    INTEGRATION_XERO_CLIENT_SECRET?: string | undefined;
    INTEGRATION_XERO_TENANT_ID?: string | undefined;
    INTEGRATION_ZOHO_CLIENT_ID?: string | undefined;
    INTEGRATION_ZOHO_CLIENT_SECRET?: string | undefined;
    INTEGRATION_ZOHO_ORGANIZATION_ID?: string | undefined;
    INTEGRATION_ODOO_BASE_URL?: string | undefined;
    INTEGRATION_ODOO_DATABASE?: string | undefined;
    INTEGRATION_ODOO_USERNAME?: string | undefined;
    INTEGRATION_ODOO_PASSWORD?: string | undefined;
    INTEGRATION_ODOO_COMPANY_ID?: string | undefined;
    INTEGRATION_ODOO_DEFAULT_JOURNAL_ID?: string | undefined;
    INTEGRATION_ODOO_DEFAULT_PRODUCT_ID?: string | undefined;
    INTEGRATION_DEAR_ACCOUNT_ID?: string | undefined;
    INTEGRATION_DEAR_API_KEY?: string | undefined;
    INTEGRATION_GOOGLE_SHEETS_CLIENT_EMAIL?: string | undefined;
    INTEGRATION_GOOGLE_SHEETS_PRIVATE_KEY?: string | undefined;
    INTEGRATION_GOOGLE_SHEETS_SPREADSHEET_ID?: string | undefined;
    INTEGRATION_EMAIL_HOST?: string | undefined;
    INTEGRATION_EMAIL_USERNAME?: string | undefined;
    INTEGRATION_EMAIL_PASSWORD?: string | undefined;
    INTEGRATION_EMAIL_PORT?: number | undefined;
    INTEGRATION_EMAIL_MAILBOX?: string | undefined;
    INTEGRATION_YIELD_PROJECT_ID?: string | undefined;
    INTEGRATION_YIELD_REGION?: string | undefined;
    INTEGRATION_PERFIOS_API_KEY?: string | undefined;
    INTEGRATION_PERFIOS_BASE_URL?: string | undefined;
    INTEGRATION_BUSINESS_CENTRAL_BASE_URL?: string | undefined;
    INTEGRATION_BUSINESS_CENTRAL_CONNECT_CLIENT_ID?: string | undefined;
    INTEGRATION_BUSINESS_CENTRAL_CONNECT_CLIENT_SECRET?: string | undefined;
    INTEGRATION_BUSINESS_CENTRAL_CONNECT_REDIRECT_URI?: string | undefined;
    INTEGRATION_BUSINESS_CENTRAL_CONNECT_DEFAULT_ENVIRONMENT?: string | undefined;
}, {
    DATABASE_URL: string;
    REDIS_URL: string;
    DEFAULT_TENANT_SLUG: string;
    JWT_ISSUER: string;
    JWT_AUDIENCE: string;
    JWT_PUBLIC_KEY: string;
    JWT_PRIVATE_KEY: string;
    INTEGRATION_NETSUITE_CLIENT_ID?: string | undefined;
    INTEGRATION_NETSUITE_CLIENT_SECRET?: string | undefined;
    INTEGRATION_NETSUITE_ACCOUNT_ID?: string | undefined;
    INTEGRATION_NETSUITE_BASE_URL?: string | undefined;
    INTEGRATION_QUICKBOOKS_CLIENT_ID?: string | undefined;
    INTEGRATION_QUICKBOOKS_CLIENT_SECRET?: string | undefined;
    INTEGRATION_QUICKBOOKS_REALM_ID?: string | undefined;
    INTEGRATION_XERO_CLIENT_ID?: string | undefined;
    INTEGRATION_XERO_CLIENT_SECRET?: string | undefined;
    INTEGRATION_XERO_TENANT_ID?: string | undefined;
    INTEGRATION_ZOHO_CLIENT_ID?: string | undefined;
    INTEGRATION_ZOHO_CLIENT_SECRET?: string | undefined;
    INTEGRATION_ZOHO_ORGANIZATION_ID?: string | undefined;
    INTEGRATION_ODOO_BASE_URL?: string | undefined;
    INTEGRATION_ODOO_DATABASE?: string | undefined;
    INTEGRATION_ODOO_USERNAME?: string | undefined;
    INTEGRATION_ODOO_PASSWORD?: string | undefined;
    INTEGRATION_ODOO_COMPANY_ID?: string | undefined;
    INTEGRATION_ODOO_DEFAULT_JOURNAL_ID?: string | undefined;
    INTEGRATION_ODOO_DEFAULT_PRODUCT_ID?: string | undefined;
    INTEGRATION_DEAR_ACCOUNT_ID?: string | undefined;
    INTEGRATION_DEAR_API_KEY?: string | undefined;
    INTEGRATION_GOOGLE_SHEETS_CLIENT_EMAIL?: string | undefined;
    INTEGRATION_GOOGLE_SHEETS_PRIVATE_KEY?: string | undefined;
    INTEGRATION_GOOGLE_SHEETS_SPREADSHEET_ID?: string | undefined;
    INTEGRATION_EMAIL_HOST?: string | undefined;
    INTEGRATION_EMAIL_USERNAME?: string | undefined;
    INTEGRATION_EMAIL_PASSWORD?: string | undefined;
    INTEGRATION_EMAIL_PORT?: number | undefined;
    INTEGRATION_EMAIL_MAILBOX?: string | undefined;
    INTEGRATION_YIELD_PROJECT_ID?: string | undefined;
    INTEGRATION_YIELD_REGION?: string | undefined;
    INTEGRATION_PERFIOS_API_KEY?: string | undefined;
    INTEGRATION_PERFIOS_BASE_URL?: string | undefined;
    NODE_ENV?: "development" | "test" | "staging" | "production" | undefined;
    LOG_LEVEL?: "info" | "error" | "debug" | "warn" | undefined;
    API_HOST?: string | undefined;
    API_PORT?: number | undefined;
    WEB_PORT?: number | undefined;
    WORKER_CONCURRENCY?: number | undefined;
    INTEGRATION_BUSINESS_CENTRAL_BASE_URL?: string | undefined;
    INTEGRATION_BUSINESS_CENTRAL_CONNECT_CLIENT_ID?: string | undefined;
    INTEGRATION_BUSINESS_CENTRAL_CONNECT_CLIENT_SECRET?: string | undefined;
    INTEGRATION_BUSINESS_CENTRAL_CONNECT_REDIRECT_URI?: string | undefined;
    INTEGRATION_BUSINESS_CENTRAL_CONNECT_DEFAULT_ENVIRONMENT?: string | undefined;
}>;
export type AppEnv = z.infer<typeof envSchema>;
//# sourceMappingURL=schema.d.ts.map